@startuml
|#AntiqueWhite|EntryGate|
|#White|Car|
start
:get random number in 0.99;
if (result < 10) then (yes)
    |#AntiqueWhite|EntryGate|
    :Enter;
    |#White|Car|
endif
:delay 0.1s;
stop
@enduml
